In [2]:
import torch
torch.__version__

'2.9.0+cu126'

In [3]:
if torch.cuda.is_available():
    print("CUDA is available")
    print(torch.cuda.get_device_name(0))
else: 
    print("CUDA is not available")

CUDA is available
Tesla T4


## Creating a Tensor

In [4]:
a = torch.empty(5, 3)

In [5]:
type(a)

torch.Tensor

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.0550, 0.1477, 0.1796],
        [0.9815, 0.0032, 0.4129]])

In [9]:
torch.manual_seed(123)
torch.rand(2,3)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])

In [10]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [12]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [13]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3], [4,5,6]])
x.shape

torch.Size([2, 3])

## Tensor Data types

In [15]:
x.dtype

torch.int64

In [16]:
torch.tensor([1.0, 2.2, 3.4], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [17]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Operations on Tensors

In [18]:
x+2

x-2

x*3 

x/3


tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

In [19]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[6, 7, 9],
        [4, 1, 1]])

In [20]:
torch.sum(e)

tensor(28)

In [21]:
torch.sum(e, dim=0) #along the columns

tensor([10,  8, 10])

In [22]:
torch.sum(e, dim=1) #along the rows

tensor([22,  6])

In [23]:
torch.mean(e, dtype=torch.float32)

tensor(4.6667)

## Inplace Operations

use function_name and then underscore to make it inplace
example: using relu on tensor inplace
m.relu_()

In [24]:
m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)

tensor([[0.0756, 0.1966, 0.3164],
        [0.4017, 0.1186, 0.8274]])
tensor([[0.3821, 0.6605, 0.8536],
        [0.5932, 0.6367, 0.9826]])


In [25]:
m.add_(n)

tensor([[0.4577, 0.8571, 1.1700],
        [0.9949, 0.7553, 1.8100]])

In [26]:
m

tensor([[0.4577, 0.8571, 1.1700],
        [0.9949, 0.7553, 1.8100]])

In [27]:
n

tensor([[0.3821, 0.6605, 0.8536],
        [0.5932, 0.6367, 0.9826]])

## Tensor Operations on CUDA

In [28]:
torch.cuda.is_available()

True

In [30]:
device = torch.device("cuda")

In [31]:
# new tensor on cuda
torch.rand((2,3), device=device)

tensor([[0.0669, 0.9448, 0.2207],
        [0.2721, 0.0079, 0.7900]], device='cuda:0')

In [33]:
# moving an existing tensor to cuda
a = torch.rand(2,3)
b = a.to(device)

In [34]:
b+5

tensor([[5.9268, 5.7388, 5.7179],
        [5.7058, 5.9156, 5.4340]], device='cuda:0')